#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# osascript -e 'tell application id "tracesOf.Uebersicht" to refresh'

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               on
#yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.8
# yabai -m config window_border                on
# yabai -m config window_border_width          1
# yabai -m config active_window_border_color   0xff4c79fe
# yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10

# ===== Rules ==================================

yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
# yabai -m rule --add label="Finder" app="^Finder$" title=".*" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="macfeh" app="^macfeh$" manage=off
yabai -m rule --add label="System Preferences" app="^System Preferences$" title=".*" manage=off
yabai -m rule --add label="System Settings" app="^System Settings$" title=".*" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="KeePassXC" app="^KeePassXC$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="mpv" app="^mpv$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Zoom" app="zoom.us" title=".*" manage=off
yabai -m rule --add label="OBS" app="OBS" title=".*" manage=off space=3
yabai -m rule --add label="EventViewer" app="EventViewer" title="EventViewer" manage=off
yabai -m rule --add label="Archive Utility" app="Archive Utility" title=".*" manage=off
# yabai -m rule --add label="lv" app="lv" title=".*" manage=off
yabai -m rule --add label="Stats" app="Stats" title=".*" manage=off
yabai -m rule --add label="Okta Verify" app="^Okta Verify$" title=".*" manage=off
yabai -m rule --add label="E-book Viewer" app="^E-book Viewer$" title=".*" manage=off
yabai -m rule --add label="Microsoft Teams" app="^Microsoft Teams.*$" title=".*" manage=off

# App placement rules
yabai -m rule --add label="Firefox" app="^Firefox$" title=".*" space=1
yabai -m rule --add label="Slack" app="^Slack$" title=".*" space=4
yabai -m rule --add label="Support Hub" app="^Support Hub$" title=".*" space=4
yabai -m rule --add label="t2" app="^t2$" title=".*" space=5

# ===== Signals =================================

# yabai -m signal -add event=application_activated action="echo \"application ID \$YABAI_PROCESS_ID activated\""

# focus window after active space changes
# yabai -m signal --add event=space_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq '.[-1].id')"
#
# focus window after active display changes
# yabai -m signal --add event=display_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq '.[-1].id')"

# ===== External Bars ===========================

# add 20 padding to the top and bottom of all spaces regardless of the display it belongs to
# yabai -m config external_bar all:30:0
